//
// Generated file, do not edit! Created by opp_msgtool 6.2 from MaxMinMessage2.msg.
//

#ifndef __MAXMINDCLUSTERPROJECT_MAXMINMESSAGE2_M_H
#define __MAXMINDCLUSTERPROJECT_MAXMINMESSAGE2_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace maxmindclusterproject {

class MaxMinMessage2;

}  // namespace maxmindclusterproject

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace maxmindclusterproject {

/**
 * Class generated from <tt>MaxMinMessage2.msg:22</tt> by opp_msgtool.
 * <pre>
 * // Inherit from FieldsChunk so it can be put inside a Packet
 * class MaxMinMessage2 extends inet::FieldsChunk
 * {
 *     int round;      // The current round number
 *     int winnerId;   // The node ID being propagated
 *     int senderId;   // Who sent this message
 * }
 * </pre>
 */
class MaxMinMessage2 : public ::inet::FieldsChunk
{
  protected:
    int round = 0;
    int winnerId = 0;
    int senderId = 0;

  private:
    void copy(const MaxMinMessage2& other);

  protected:
    bool operator==(const MaxMinMessage2&) = delete;

  public:
    MaxMinMessage2();
    MaxMinMessage2(const MaxMinMessage2& other);
    virtual ~MaxMinMessage2();
    MaxMinMessage2& operator=(const MaxMinMessage2& other);
    virtual MaxMinMessage2 *dup() const override {return new MaxMinMessage2(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRound() const;
    virtual void setRound(int round);

    virtual int getWinnerId() const;
    virtual void setWinnerId(int winnerId);

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaxMinMessage2& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaxMinMessage2& obj) {obj.parsimUnpack(b);}


}  // namespace maxmindclusterproject


namespace omnetpp {

template<> inline maxmindclusterproject::MaxMinMessage2 *fromAnyPtr(any_ptr ptr) { return check_and_cast<maxmindclusterproject::MaxMinMessage2*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MAXMINDCLUSTERPROJECT_MAXMINMESSAGE2_M_H

