//
// Generated file, do not edit! Created by opp_msgtool 6.2 from MaxMinMessage.msg.
//

#ifndef __MAXMINMESSAGE_M_H
#define __MAXMINMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MaxMinMessage;
/**
 * Class generated from <tt>MaxMinMessage.msg:17</tt> by opp_msgtool.
 * <pre>
 * // MaxMinMessage.msg
 * message MaxMinMessage
 * {
 *     int round;      // The current round number (1 to 2d)
 *     int winnerId;   // The node ID being propagated
 *     int senderId;   // Who sent this message (for SENDER array)
 * }
 * </pre>
 */
class MaxMinMessage : public ::omnetpp::cMessage
{
  protected:
    int round = 0;
    int winnerId = 0;
    int senderId = 0;

  private:
    void copy(const MaxMinMessage& other);

  protected:
    bool operator==(const MaxMinMessage&) = delete;

  public:
    MaxMinMessage(const char *name=nullptr, short kind=0);
    MaxMinMessage(const MaxMinMessage& other);
    virtual ~MaxMinMessage();
    MaxMinMessage& operator=(const MaxMinMessage& other);
    virtual MaxMinMessage *dup() const override {return new MaxMinMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRound() const;
    virtual void setRound(int round);

    virtual int getWinnerId() const;
    virtual void setWinnerId(int winnerId);

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaxMinMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaxMinMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline MaxMinMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<MaxMinMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MAXMINMESSAGE_M_H

